!!python/object/apply:collections.OrderedDict
- - - ent_coef
    - 0.0
  - - gamma
    - 0.99
  - - lam
    - 0.94
  - - n_envs
    - 16
  - - n_steps
    - 256
  - - n_timesteps
    - 1000000.0
  - - nminibatches
    - 8
  - - noptepochs
    - 4
  - - normalize
    - true
  - - policy
    - MlpPolicy
